title: Satish Lokkoju
description: Thoughts and other musings 
theme: jekyll-theme-modernist
github:
  owner_name: Satish Lokkoju
  linkedin: https://www.linkedin.com/in/lsatish
  resume: https://www.linkedin.com/in/lsatish
  repository_url: https://www.github.com/satishlokkoju
website:
  url: http://satishlokkoju.github.io
  shortened: Satish Lokkoju