title: Satish Lokkoju
description: Thoughts and other musings 
theme: jekyll-theme-modernist
github:
  owner_name: Satish Lokkoju
  linkedin: https://www.linkedin.com/in/lsatish
  resume: https://www.linkedin.com/in/lsatish
  repository_url: https://www.github.com/satishlokkoju
contact:
  mail: mailto:satish.lokkoju@gmail.com?subject=hello satish
website:
  url: http://satishlokkoju.github.io
  shortened: Satish Lokkoju
strings:
  about_me: About Me
  name: Satish Lokkoju

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 22
paginate_path: "/page:num/"

permalink: pretty

future: true
