name: Build and Deploy Astro Site

on:
  push:
    paths:
      - 'astro-src/**'
      - '.github/workflows/astro-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: astro-src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Copy build to root
        run: |
          rm -rf ../!(astro-src|.git|.github|.gitignore)
          cp -r dist/* ../

      - name: Commit and push changes
        run: |
          cd ..
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-build and deploy Astro site [skip ci]" || echo "No changes to commit"
          git push
